version: "3"

services:
  app:
    container_name: mynodecontainer
    restart: always
    build: .
    command: npm start
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - mongo
  mongo:
    container_name: mymongodbcontainer
    image: mongo:4.2.16
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
volumes:
 mongodb: